package merkle

import (
	"bytes"
	"testing"
)

// TestConsistency_ExhaustiveRoundTrip is the decisive validation: for every tree size n up to 40 and
// every earlier size m in [1, n], the proof generated by ConsistencyProof must let VerifyConsistency
// reconstruct BOTH the independently computed earlier root (Root of the first m leaves) and the
// later root (Root of all n leaves). If the prover and verifier disagree, or either is wrong, this
// fails.
func TestConsistency_ExhaustiveRoundTrip(t *testing.T) {
	for n := 1; n <= 40; n++ {
		all := leaves(n)
		root2 := Root(all)
		for m := 1; m <= n; m++ {
			root1 := Root(all[:m])
			proof := ConsistencyProof(all, m)
			if !VerifyConsistency(m, n, proof, root1, root2) {
				t.Fatalf("n=%d m=%d: valid consistency proof did not verify (proof len %d)", n, m, len(proof))
			}
		}
	}
}

func TestConsistency_TamperingFails(t *testing.T) {
	all := leaves(13)
	root2 := Root(all)
	m := 5
	root1 := Root(all[:m])
	proof := ConsistencyProof(all, m)
	if !VerifyConsistency(m, n(all), proof, root1, root2) {
		t.Fatal("baseline consistency proof should verify")
	}

	// Wrong earlier root (claims a different history).
	if VerifyConsistency(m, n(all), proof, Root(all[:m+1]), root2) {
		t.Error("a wrong root1 must not verify")
	}
	// Wrong later root.
	if VerifyConsistency(m, n(all), proof, root1, Root(all[:12])) {
		t.Error("a wrong root2 must not verify")
	}
	// Tampered proof node.
	if len(proof) > 0 {
		bad := make([][]byte, len(proof))
		copy(bad, proof)
		bad[0] = bytes.Repeat([]byte{0xaa}, 32)
		if VerifyConsistency(m, n(all), bad, root1, root2) {
			t.Error("a tampered proof node must not verify")
		}
	}
	// Wrong (swapped) sizes.
	if VerifyConsistency(n(all), m, proof, root2, root1) {
		t.Error("m > n must not verify")
	}
	// Non-32-byte proof node.
	if len(proof) > 0 {
		bad := make([][]byte, len(proof))
		copy(bad, proof)
		bad[0] = bytes.Repeat([]byte{0x00}, 31)
		if VerifyConsistency(m, n(all), bad, root1, root2) {
			t.Error("a short proof node must not verify")
		}
	}
}

func TestConsistency_IdenticalSizeIsEmptyProof(t *testing.T) {
	all := leaves(7)
	root := Root(all)
	if p := ConsistencyProof(all, 7); len(p) != 0 {
		t.Errorf("m==n proof should be empty, got %d", len(p))
	}
	if !VerifyConsistency(7, 7, nil, root, root) {
		t.Error("m==n with equal roots and empty proof should verify")
	}
	if VerifyConsistency(7, 7, nil, root, Root(leaves(6))) {
		t.Error("m==n with different roots must not verify")
	}
}

func TestConsistency_PowerOfTwoBoundaryOmitsRoot1(t *testing.T) {
	// When m is a power of two, the proof omits root1 (the verifier already has it). Exercise m=4,8.
	for _, m := range []int{4, 8} {
		all := leaves(m + 3)
		if !VerifyConsistency(m, m+3, ConsistencyProof(all, m), Root(all[:m]), Root(all)) {
			t.Errorf("power-of-two m=%d consistency proof did not verify", m)
		}
	}
}

func n(s [][]byte) int { return len(s) }
