"""Two-level envelope key hierarchy.

Each memory row is encrypted under a fresh per-row data key. That data key is wrapped under a
per-subject key. The per-subject key is itself wrapped by KMS (see kms.py) and stored exactly once
in the subject_keys row. Erasing a subject deletes that one row, so every per-row data key becomes
permanently unwrappable while the ciphertext survives as provable noise.

This module implements the local wrapping (data key under subject key). The outermost wrap of the
subject key is done by AWS KMS in kms.py; here the subject key is treated as opaque key material.
"""

from __future__ import annotations

from dataclasses import dataclass

from cryptography.hazmat.primitives.keywrap import (
    InvalidUnwrap,
    aes_key_unwrap,
    aes_key_wrap,
)

from . import aead

__all__ = ["InvalidUnwrap", "new_subject_key", "new_data_key", "wrap_data_key", "unwrap_data_key",
           "RowKeyMaterial"]


def new_subject_key() -> bytes:
    """A 256-bit per-subject key. In production this is generated by KMS GenerateDataKey."""
    return aead.generate_key()


def new_data_key() -> bytes:
    """A 256-bit per-row data key."""
    return aead.generate_key()


@dataclass(frozen=True)
class RowKeyMaterial:
    """A per-row data key wrapped under the subject key, stored as agent_memory.wrapped_key."""

    wrapped: bytes


def wrap_data_key(subject_key: bytes, data_key: bytes) -> RowKeyMaterial:
    """Wrap a per-row data key under the subject key (RFC 3394 AES key wrap)."""
    return RowKeyMaterial(wrapped=aes_key_wrap(subject_key, data_key))


def unwrap_data_key(subject_key: bytes, material: RowKeyMaterial) -> bytes:
    """Recover a per-row data key. Raises InvalidUnwrap if the subject key is wrong or destroyed.

    Once the subject key is gone (its subject_keys row deleted and its KMS wrap unavailable), no
    caller can produce the subject_key argument, so no data key can be unwrapped: the whole
    subject's memory is cryptographically erased by deleting one row.
    """
    return aes_key_unwrap(subject_key, material.wrapped)
