"""AWS KMS: the envelope path and the imported-material kill switch.

Two mechanisms, both honest crypto-erasure per NIST SP 800-88 Rev. 2:

1. Envelope (primary, used for every subject): GenerateDataKey returns a plaintext data key and a
   KMS-wrapped copy. We encrypt with the plaintext key (see aead.py) and store only the wrapped
   copy. Erasure deletes that wrapped copy from CockroachDB, so the data key can never be recovered.
   The subject_id is bound as the KMS encryption context, so a wrapped key cannot be decrypted under
   a different subject.

2. Imported material (the demo subject's second, independent kill switch): a per-subject CMK created
   with Origin=EXTERNAL, whose key material we generate locally, wrap under the KMS-provided RSA
   public key (RSAES_OAEP_SHA_256), and import. DeleteImportedKeyMaterial then makes the key
   immediately unusable with no AWS-side recovery. We poll DescribeKey until KeyState=PendingImport
   because the delete is subject to eventual consistency.

The plaintext data key and the imported key material are never persisted or logged. That is the
forward-secrecy condition the NIST technique requires.
"""

from __future__ import annotations

import time
from dataclasses import dataclass

import boto3
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa


@dataclass(frozen=True)
class DataKey:
    """A freshly generated data key: the plaintext (use then discard) and its wrapped copy."""

    plaintext: bytes
    wrapped: bytes


class KMS:
    """Thin wrapper over the boto3 KMS client, region-bound."""

    def __init__(self, region: str, client=None):
        self._kms = client or boto3.client("kms", region_name=region)

    # --- Envelope path ---

    def generate_data_key(self, key_id: str, subject_id: str) -> DataKey:
        """Generate a 256-bit data key bound to subject_id via the KMS encryption context."""
        resp = self._kms.generate_data_key(
            KeyId=key_id, KeySpec="AES_256", EncryptionContext={"subject_id": subject_id}
        )
        return DataKey(plaintext=resp["Plaintext"], wrapped=resp["CiphertextBlob"])

    def decrypt_data_key(self, wrapped: bytes, subject_id: str) -> bytes:
        """Recover a data key. The encryption context must match, or KMS refuses."""
        resp = self._kms.decrypt(
            CiphertextBlob=wrapped, EncryptionContext={"subject_id": subject_id}
        )
        return resp["Plaintext"]

    # --- Imported-material kill switch ---

    def provision_imported_key(self, description: str, material: bytes) -> str:
        """Create an EXTERNAL-origin CMK and import `material` (32 bytes) under it. Returns the ARN.

        `material` is generated by the caller and never persisted; this method wraps it under the
        KMS-provided RSA public key and imports it, so plaintext material never leaves memory.
        """
        if len(material) != 32:
            raise ValueError("imported key material must be 32 bytes")
        key = self._kms.create_key(
            Origin="EXTERNAL", KeySpec="SYMMETRIC_DEFAULT", Description=description
        )["KeyMetadata"]
        key_id = key["KeyId"]
        params = self._kms.get_parameters_for_import(
            KeyId=key_id,
            WrappingAlgorithm="RSAES_OAEP_SHA_256",
            WrappingKeySpec="RSA_2048",
        )
        wrapped = self._wrap_material(params["PublicKey"], material)
        self._kms.import_key_material(
            KeyId=key_id,
            ImportToken=params["ImportToken"],
            EncryptedKeyMaterial=wrapped,
            ExpirationModel="KEY_MATERIAL_DOES_NOT_EXPIRE",
        )
        return key.get("Arn", key_id)

    def destroy_imported_key(self, key_id: str, timeout_s: float = 10.0) -> str:
        """DeleteImportedKeyMaterial, then poll DescribeKey until KeyState=PendingImport.

        The delete call is the destructive operation: if IT raises, that propagates (a real
        failure). Once it succeeds the material is gone; only the confirmation is eventually
        consistent. So the confirmation poll's DescribeKey reads are guarded, and if we cannot
        confirm within the timeout we return "Unconfirmed" (delete succeeded, state not yet
        observed) rather than letting a read-side error masquerade as a destroy failure. The caller
        must treat "PendingImport" as destroyed and anything else as pending confirmation, never as
        "not destroyed".
        """
        self._kms.delete_imported_key_material(KeyId=key_id)  # destructive; propagate on error
        deadline = time.monotonic() + timeout_s
        state = "Unconfirmed"
        while time.monotonic() < deadline:
            try:
                state = self.key_state(key_id)
            except Exception:  # noqa: BLE001 -- a read error after a successful delete is not a failure
                state = "Unconfirmed"
            if state == "PendingImport":
                return state
            time.sleep(0.25)
        return state

    def key_state(self, key_id: str) -> str:
        return self._kms.describe_key(KeyId=key_id)["KeyMetadata"]["KeyState"]

    @staticmethod
    def _wrap_material(public_key_der: bytes, material: bytes) -> bytes:
        """RSAES_OAEP_SHA_256-wrap the key material under the KMS-provided RSA public key."""
        public_key = serialization.load_der_public_key(public_key_der)
        if not isinstance(public_key, rsa.RSAPublicKey):
            raise TypeError("KMS import public key is not RSA")
        return public_key.encrypt(
            material,
            padding.OAEP(
                mgf=padding.MGF1(algorithm=hashes.SHA256()),
                algorithm=hashes.SHA256(),
                label=None,
            ),
        )
