"""Compute canonical GTR-base embeddings for the seed corpus so the demo runs on real (not
synthetic) data. Embedding is CPU-only; only Vec2Text inversion needs a GPU, so this runs anywhere.

The embedding MUST match the pipeline the Vec2Text corrector was trained on and that spike1 used:
mean-pool the gtr-t5-base encoder's last hidden state over the attention mask, UNNORMALIZED
(SentenceTransformer.encode normalizes and would degrade reconstruction). See
spikes/spike1_vec2text/spike1_modal.py.

Usage (from repo root, in a venv with torch + transformers==4.44.2 + sentencepiece):
    python db/seed/embed_corpus.py

Reads db/seed/corpus.json, writes db/seed/corpus_embedded.json with, per memory:
  id, text, content_b64 (base64 of the UTF-8 sentence), embedding_b64 (base64 of 768 little-endian
  float32), embedding_sha256 (hex, so the app can prove a recorded run is of THIS vector).
"""

import base64
import hashlib
import json
import pathlib

import torch
from transformers import AutoModel, AutoTokenizer

MODEL = "sentence-transformers/gtr-t5-base"
SEED_DIR = pathlib.Path(__file__).resolve().parent


def mean_pool(hidden: "torch.Tensor", mask: "torch.Tensor") -> "torch.Tensor":
    m = mask.unsqueeze(-1).float()
    return (hidden * m).sum(1) / m.sum(1).clamp(min=1e-9)


def main() -> None:
    corpus = json.loads((SEED_DIR / "corpus.json").read_text())

    tokenizer = AutoTokenizer.from_pretrained(MODEL)
    base = AutoModel.from_pretrained(MODEL)
    encoder = (base.encoder if hasattr(base, "encoder") else base).eval()

    out_memories = []
    for mem in corpus["memories"]:
        text = mem["text"]
        inp = tokenizer(
            [text],
            return_tensors="pt",
            max_length=128,
            truncation=True,
            padding="max_length",
        )
        with torch.no_grad():
            hidden = encoder(
                input_ids=inp["input_ids"], attention_mask=inp["attention_mask"]
            ).last_hidden_state
            emb = mean_pool(hidden, inp["attention_mask"])[0]

        vec_bytes = emb.detach().cpu().numpy().astype("<f4").tobytes()  # 768 * 4 = 3072
        if len(vec_bytes) != 768 * 4:
            raise ValueError(f"expected 3072 embedding bytes, got {len(vec_bytes)}")
        out_memories.append(
            {
                "id": mem["id"],
                "text": text,
                "content_b64": base64.b64encode(text.encode("utf-8")).decode(),
                "embedding_b64": base64.b64encode(vec_bytes).decode(),
                "embedding_sha256": hashlib.sha256(vec_bytes).hexdigest(),
            }
        )

    result = {
        "consent": corpus["consent"],
        "model": corpus["model"],
        "note": "Generated by db/seed/embed_corpus.py. Real GTR-base embeddings, not synthetic.",
        "memories": out_memories,
    }
    (SEED_DIR / "corpus_embedded.json").write_text(json.dumps(result, indent=2) + "\n")
    print(f"wrote corpus_embedded.json with {len(out_memories)} real embeddings")
    for m in out_memories:
        print(f"  {m['id']}: sha256={m['embedding_sha256'][:16]}...  text={m['text']!r}")


if __name__ == "__main__":
    main()
